package dev.glory.java14.record;

import java.util.Objects;

/*
https://www.baeldung.com/java-record-keyword

Records are immutable data classes that require only the type and name of fields.
The equals, hashCode, and toString methods, as well as the private, final fields and public constructor, are generated by the Java compiler.

1. private, final field for each piece of data
2. getter for each field
3. public constructor with a corresponding argument for each field
4. equals method that returns true for objects of the same class when all fields match
5. hashCode method that returns the same value when all fields match
6. toString method that includes the name of the class and the name of each field and its corresponding value
 */
public record Person(String name, Integer age) {

    public Person {
        Objects.requireNonNull(name);
        Objects.requireNonNull(age);
    }

    public Person(String name) {
        this(name, 10);
    }

    public static Person unnamed(int age) {
        return new Person("Unnamed", age);
    }
}
